#!/bin/bash
#
# theme-rebuild
# John Simpson <jms1@jms1.net> 2026-03-12 thu
LAST_UPDATED='2026-07-24 Fri'
#
# Rebuild the theme files in the theme-template/ directory.
# - Run 'mdbook-fix-templates', which builds new *.hbs and
#   css/variables.css files
# - Copy all css/*.css files to theme/css/
#
# NOTE: it's important that nothing in this script sends anything to STDOUT,
# other than the `jq` command. This is why every other command in the script
# has `1>&2`, to send any possible output to STDERR.

###############################################################################
###############################################################################
###############################################################################
#
# Make sure the tools we need are available. If not, you should either install
# them, or updae the PATH= line above and make sure the directories where the
# tools are installed, are present in the PATH.

TOOLS=( jq )

FAIL=false
for X in "${TOOLS[@]}"
do
    if ! type -t "$X" > /dev/null
    then
        echo "ERROR: '$X' is not available in your PATH, cannot continue"
        FAIL=true
    fi
done

if $FAIL
then
    exit 1
fi

###############################################################################
#
# Print the second element from the JSON structure, without any modifications.

jq -r -M '.[1]'

###############################################################################
#
# Maybe rebuild the `*.hbs` and `css/variables.css` files
# in the theme-template/ directory.

( cd theme-template ; ./mdbook-fix-templates -q ) 1>&2

########################################
# Copy the CSS files

mkdir -p theme/css 1>&2
cp theme-template/css/*.css theme/css/ 1>&2
