#!/usr/bin/env perl
#
# mdbook-fix-templates
# jms1 2022-04-05
my $VERSION = 'v0.5.0 2026-03-12' ;
#
# Copy or update mdbook template files for "books".
#
# Previous versions of this script required that you have a copy of the
# mdbook source code cloned on the machine where the script runs. This is no
# longer necessary, the script now downloads the original template files
# from the mdbook source code repo on Github.
#
###############################################################################
#
# MIT License
#
# Copyright (c) 2022-2026 John Simpson
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
###############################################################################

require 5.005 ;
use strict ;
use warnings ;

use Cwd qw 'abs_path cwd' ;
use Getopt::Std ;
use LWP::UserAgent ;

########################################
# Global variables

my %opt             = () ;      # getopts
my $do_backups      = 0 ;       # -b
my $customs_first   = 0 ;       # -f

my $above_toc       = '' ;      # HTML fragment for above the ToC
my $below_toc       = '' ;      # HTML fragment for below the ToC
my $below_page      = '' ;      # HTML fragment for below the main page
my $mdbook_ver      = '' ;      # mdbook version we're running
my %themes          = () ;      # display names of custom themes

########################################
# URLs of the mdbook source code's `front-end/` directories. This program
# will download original template and CSS files from here. The actual
# version will be substituted where "_TAG_" appears in the value.
#
# Note that the keys in this hash will be evaluated as regular expressions
# with '^' before them, so 'v0.5.' will match all v0.5.x tags.

my %ver_url     = (
    'v0\.4\.' => 'https://raw.githubusercontent.com/rust-lang/mdBook/refs/tags/_TAG_/src/front-end/' ,
    'v0\.5\.' => 'https://raw.githubusercontent.com/rust-lang/mdBook/refs/tags/_TAG_/crates/mdbook-html/front-end/' ,
) ;

###############################################################################
#
# Coloured line functions

sub redline(@)
{
    printf "\e[0;1;37;41m%s\e[0K\e[0m\n" , join( ' ' , @_ ) ;
}

sub fail(@) {
    redline( @_ ) ;
    exit 1 ;
}

###############################################################################
#
# Usage

sub usage(;$) {
    my $msg = ( shift || '' ) ;

    print <<EOF ;
$0 [OPTIONS]
$VERSION

Copy or update mdbook templates files.

This script must be run in a book's "theme-template/" directory.

This script will download the original template and CSS files it needs from
the mdbook source code repo on Github. They will be stored in the current
directory, and the 'copy-css' and 'version-commit' scripts will use them to
build the files in the "theme/" directory every time the book is rendered.

-b      Create backups of each file before writing it.

-f      Insert the custom theme names at the beginning of the list in the
        drop-down menu. Without this, the custom theme names will be added
        to the end of the list.

-h      Show this help message.

EOF

    if ( $msg ne '' )
    {
        fail( $msg ) ;
    }

    exit 0 ;
}

###############################################################################
#
# If a file exists, rename it to the same name with ".old" at the end

sub rename_file_old($)
{
    my $file = shift ;

    if ( $do_backups )
    {
        if ( -f $file )
        {
            print "renaming    $file to $file.old\n" ;

            rename( $file , "$file.old" )
                or fail( "ERROR: can't rename \"$file\" to \"$file.old\": $!\n" ) ;
        }
    }
}

###############################################################################
#
# Read a file's contents into a variable. If the file doesn't exist, return
# an empty string.

sub readfile_maybe($)
{
    my $file = shift ;
    my $rv   = '' ;

    print "reading     $file\n" ;

    if ( -f $file )
    {
        open( my $fh , '<' , $file )
            or fail( "ERROR: can't read \"$file\": $!\n" ) ;

        local $/ ;
        $rv = <$fh> ;

        close $fh ;
    }

    return $rv ;
}

###############################################################################
#
# Get the output of a command

sub command_output($)
{
    my $cmd = shift ;

    open( my $fh , "$cmd |" )
        or fail( "ERROR: '$cmd' failed: $!\n" ) ;

    local $/ ;
    my $text = <$fh> ;
    close $fh ;

    return $text ;
}

###############################################################################
#
# Return the contents of a template or CSS file from the mdbook source
# - download it if it doesn't already exist

sub get_original_file($$)
{
    my $version = shift ;
    my $file    = shift ;

    ############################################################
    # If the file already exists, return its contents

    if ( -f "$version/$file" )
    {
        return readfile_maybe( "$version/$file" ) ;
    }

    ############################################################
    # Need to download the file from Github

    ########################################
    # Figure out the URL to download

    my $url = '' ;
    for my $k ( sort keys %ver_url )
    {
        if ( $version =~ m|^$k| )
        {
            $url = $ver_url{$k} ;
            last ;
        }
    }

    if ( $url eq '' )
    {
        fail( "ERROR: don't know how to download templates for mdbook version $version" ) ;
    }

    $url =~ s|_TAG_|$version|g ;

    if ( $file =~ m|\.hbs$| )
    {
        $url =~ s|/?$|/templates/$file| ;
    }
    elsif ( $file =~ m|\.css$| )
    {
        $url =~ s|/?$|/css/$file| ;
    }
    else
    {
        fail( "ERROR: don't know how to download '$file' from Github" ) ;
    }

    ########################################
    # Create the version's directory if it doesn't exist

    if ( ! -d $version )
    {
        print "mkdir       $version\n" ;

        mkdir( $version , 0755 )
            or die "ERROR: mkdir('$version'): $!\n" ;
    }

    ########################################
    # Download the file
    # TODO: handle redirects

    print "downloading $url\n" ;

    my $ua = new LWP::UserAgent( "mdbook-fix-templates/$VERSION" ) ;
    my $res = $ua->get( $url ) ;

    if ( $res->code() !~ m|^2| )
    {
        print "ERROR: download failed\n" ;
        print $res->status_line() , "\n" ;
        exit 1 ;
    }

    my $rv = $res->content() ;

    ########################################
    # Save the file

    print "writing     $version/$file\n" ;

    open( my $fh , '>' , "$version/$file" )
        or die "ERROR: can't write '$version/$file': $!\n" ;
    print $fh $rv ;
    close $fh ;

    ########################################
    # Return the cotent

    return $rv ;
}

###############################################################################
#
# Update 'index.hbs' - template for main content area

sub update_index_hbs()
{
    ########################################
    # Initialize variables

    my $mdbook_theme_list   = 0 ;
    my $indent              = '' ;
    my $ipre                = '' ;

    if ( $mdbook_ver ge 'v0.5.' )
    {
        $ipre = 'mdbook-theme-' ;
    }

    ########################################
    # Build the list of themes

    my $custom_themes = '' ;

    for my $dname ( sort keys %themes )
    {
        $custom_themes ||= "<!-- Start custom themes -->\n" ;

        my $iname = $themes{$dname} ;

        $custom_themes .= <<EOF ;
$indent<li role="none"><button role="menuitem" class="theme" id="$ipre$iname">$dname</button></li>
EOF
    }

    if ( $custom_themes ne '' )
    {
        $custom_themes .= "<!-- End custom themes -->\n" ;
    }

    ########################################
    # Read (possibly download) the original 'index.hbs' file

    rename_file_old( 'index.hbs' ) ;
    my $orig = get_original_file( $mdbook_ver , 'index.hbs' ) ;

    ############################################################
    # Write the output file

    print "writing     index.hbs\n" ;

    open( my $o , '>' , "index.hbs" )
        or fail( "ERROR: can't write 'index.hbs': $!\n" ) ;

    $mdbook_theme_list = 0 ;
    for my $line ( split( m|\n|s , $orig ) )
    {
        ########################################
        # If this line contains 'id="mdbook-theme-list"', set a flag to
        # remember we're in the list. This flag is needed if we're adding
        # the custom themes to the bottom of the list.

        if ( $line =~ m|id="mdbook-theme-list"| )
        {
            $mdbook_theme_list = 1 ;
        }

        ########################################
        # If we're within the theme list ...

        if ( $mdbook_theme_list )
        {
            ########################################
            # If this is an existing <li> within the list, remember how
            # much whitespace is before the <li> tag so we can indent our
            # output the same amount

            if ( $line =~ m|^(\s*)<li| )
            {
                $indent = $1 ;
            }

            ########################################
            # If we're adding the custom list to the top, and the current
            # line is the <li> whose title is "Auto"
            # - print the current line
            # - print the custom theme list
            # - clear the "in the list" flag
            # - skip to the next line (i.e. don't print the current line below)

            if ( $customs_first )
            {
                if ( $line =~ m|>Auto<| )
                {
                    print $o "$line\n" ;
                    print $o $custom_themes ;
                    $mdbook_theme_list = 0 ;
                    next ;
                }
            }

            ########################################
            # If we're adding the custom list to the bottom, and the current
            # line is the end of the list
            # - print the custom theme list
            # - clear the "in the list" flag

            elsif ( $line =~ m|</ul>| )
            {
                print $o $custom_themes ;

                $mdbook_theme_list = 0 ;
            }
        }

        ########################################
        # Print the line we received

        print $o "$line\n" ;

        ########################################
        # If this line contained the {{{content}}} tag,
        # print the footer

        if ( $line =~ m|\{\{\{\s*content\s*\}\}\}| )
        {
            print $o $below_page ;
        }
    }

    print $o "<!-- mdbook-fix-templates $VERSION - mdbook $mdbook_ver -->\n" ;

    close $o ;
}

###############################################################################
#
# Update 'toc.html.hbs' - template for ToC without javascript

sub update_toc_html_hbs()
{
    rename_file_old( 'toc.html.hbs' ) ;

    my $orig = get_original_file( $mdbook_ver , 'toc.html.hbs' ) ;

    print "writing     toc.html.hbs\n" ;

    open( my $o , '>' , "toc.html.hbs" )
        or fail( "ERROR: can't write 'toc.html.hbs': $!\n" ) ;

    for my $line ( split( m|\n|s , $orig ) )
    {
        if ( $line =~ m|\{\{\s*#toc\s*\}\}\s*\{\{\s*/toc\s*\}\}| )
        {
            print $o $above_toc , "$line\n" , $below_toc ;
        }
        else
        {
            print $o "$line\n" ;
        }
    }

    print $o "<!-- mdbook-fix-templates $VERSION - mdbook $mdbook_ver -->\n" ;

    close $o ;
}

###############################################################################
#
# Update 'toc.js.hbs' - template for ToC with javascript

sub update_toc_js_hbs()
{
    rename_file_old( 'toc.js.hbs' ) ;

    my $orig = get_original_file( $mdbook_ver , 'toc.js.hbs' ) ;

    print "writing     toc.js.hbs\n" ;

    open( my $o , '>' , "toc.js.hbs" )
        or fail( "ERROR: can't write 'toc.js.hbs': $!\n" ) ;

    for my $line ( split( m|\n|s , $orig ) )
    {
        if ( $line =~ m|^(.*?)(\{\{\s*#toc\s*\}\}\s*\{\{\s*/toc\s*\}\})(.*?)$| )
        {
            my ( $before , $tags , $after ) = ( $1 , $2 , $3 ) ;

            ########################################
            # the javascript string where the items are being inserted must
            # be a multi-line string (delimited by backticks)

            $before =~ s|['"]$|`| ;
            $after  =~ s|^['"]|`| ;

            print $o "$before$above_toc$tags$below_toc$after\n" ;
        }
        else
        {
            print $o "$line\n" ;
        }
    }

    print $o "\n// mdbook-fix-templates $VERSION - mdbook $mdbook_ver\n" ;

    close $o ;
}

###############################################################################
#
# Update 'variables.css' - sets variable values used by CSS files

sub update_variables_css()
{
    rename_file_old( 'variables.css' ) ;

    ########################################
    # Read the original 'variables.css' file into memory

    my $orig = get_original_file( $mdbook_ver , 'variables.css' ) ;

    ########################################
    # If we have any custom CSS files, read them into memory
    # - parse themes' display names from CSS filenames

    my $add_css = '' ;
    my $count   = 0 ;
    %themes     = () ;

    for my $f ( glob( "themes/*.css" ) )
    {
        print "reading     $f\n" ;

        $count ++ ;

        ########################################
        # Parse the theme's display name from the filename

        my $dname = $f ;
        $dname =~ s|^.*/|| ;
        $dname =~ s|\.css||i ;

        ########################################
        # Read the file into memory
        # - the first ".xxx {" line contains the theme's internal name

        $add_css .= "/* start '$dname' from $f */\n" ;

        my $iname = '' ;

        open( my $fh , '<' , $f )
            or fail( "ERROR: can't read '$f': $!" ) ;
        while ( my $line = <$fh> )
        {
            $add_css .= $line ;

            if ( $line =~ m|^.(\S+).*{\s*$| && ( $iname eq '' ) )
            {
                $iname = $1 ;
            }
        }
        close $fh ;

        $add_css .= "/* end '$dname' */\n" ;

        ########################################
        # Remember the "display name => internal name" association

        if ( $iname eq '' )
        {
            fail( "ERROR: no '.xxx {' line found in '$f'" ) ;
        }

        $themes{$dname} = $iname ;
    }

    ########################################
    # If the 'css' directory doesn't exist, create it

    if ( ! -d 'css' )
    {
        print "mkdir       ./css\n" ;
        mkdir( 'css' , 0755 )
            or fail( "ERROR: mkdir('css'): $!" ) ;
    }

    ############################################################
    # Write the modified file

    print "writing     css/variables.css\n" ;

    open( my $o , '>' , "css/variables.css" )
        or fail( "ERROR: can't write 'css/variables.css': $!\n" ) ;

    for my $line ( split( m|\n|s , $orig ) )
    {
        if ( $line =~ m|^\s*\@media \(prefers\-color\-scheme: dark\)\s*\{| )
        {
            print $o "/* start CSS additions (custom theme values) */\n" ;
            print $o $add_css ;
            print $o "/* end CSS additions (custom theme values) */\n\n" ;
        }

        print $o "$line\n" ;
    }

    print $o "\n/* mdbook-fix-templates $VERSION - mdbook $mdbook_ver */\n" ;

    close $o ;
}

###############################################################################
###############################################################################
###############################################################################

getopts( 'hbf' , \%opt ) ;
$opt{'h'} && usage() ;
$do_backups     = ( $opt{'b'} ? 1 : 0 ) ;
$customs_first  = ( $opt{'f'} ? 1 : 0 ) ;

###############################################################################
#
# Make sure the script is running in a book's "theme-template" directory.

if ( abs_path( cwd() ) !~ m|/theme-template$| )
{
    usage( "ERROR: this script needs to run in a book's \"theme-template\" directory\n" ) ;
}

########################################
# Figure out what version of mdbook we're running

$mdbook_ver = command_output( 'mdbook --version' ) ;
chomp $mdbook_ver ;
$mdbook_ver =~ s|^mdbook || ;

if ( $mdbook_ver eq '' )
{
    fail "ERROR: 'mdbook --version' failed: $!" ;
}

print "mdbook      $mdbook_ver\n" ;

########################################
# Read the HTML fragment files into memory
# - if a file doesn't exist, readfile_mabye() returns an empty string

$above_toc  = readfile_maybe( 'above-toc.html' ) ;
$below_toc  = readfile_maybe( 'below-toc.html' ) ;
$below_page = readfile_maybe( 'below-page.html' ) ;

########################################
# Modify and write the files
# - must process variables.css first, it builds the list of custom themes

update_variables_css() ;
update_index_hbs() ;
update_toc_html_hbs() ;
update_toc_js_hbs() ;
